### ISSUE TITLE
WIN32 clang-cl: 'extern' is invalid in friend declarations

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/llfio#105]
**Describe the bug**
`clang-cl` fails to compile `fs_handle.hpp/to_win32_path` due to the friend declaration containing the `extern` linkage specifier.
```
  In file included from C:\devel\source\deeplex\concrete\build\x64-windows-clang\vcpkg_installed\x64-windows-static\include\llfio/llfio.hpp:18:
  In file included from C:\devel\source\deeplex\concrete\build\x64-windows-clang\vcpkg_installed\x64-windows-static\include\llfio/v2.0/llfio.hpp:65:
  In file included from C:\devel\source\deeplex\concrete\build\x64-windows-clang\vcpkg_installed\x64-windows-static\include\llfio/v2.0/directory_handle.hpp:28:
  In file included from C:\devel\source\deeplex\concrete\build\x64-windows-clang\vcpkg_installed\x64-windows-static\include\llfio/v2.0/path_discovery.hpp:28:
C:\devel\source\deeplex\concrete\build\x64-windows-clang\vcpkg_installed\x64-windows-static\include\llfio\v2.0\fs_handle.hpp(175,12): error : 'extern' is invalid in friend declarations
      friend LLFIO_HEADERS_ONLY_FUNC_SPEC result<filesystem::path>
             ^
  C:\devel\source\deeplex\concrete\build\x64-windows-clang\vcpkg_installed\x64-windows-static\include\llfio/v2.0/config.hpp(464,38): note: expanded from macro 'LLFIO_HEADERS_ONLY_FUNC_SPEC'
  #define LLFIO_HEADERS_ONLY_FUNC_SPEC extern LLFIO_DECL
```
https://github.com/ned14/llfio/blob/f8d2eebeb1742a5ebec4da856d47ba6fd1a48a8c/include/llfio/v2.0/fs_handle.hpp#L121-L122
https://github.com/ned14/llfio/blob/f8d2eebeb1742a5ebec4da856d47ba6fd1a48a8c/include/llfio/v2.0/fs_handle.hpp#L156-L157

**To Reproduce / MCVE**
```cpp
#include <llfio/llfio.hpp>
```
`clang-cl.exe  /nologo -TP -DLLFIO_EXPERIMENTAL_STATUS_CODE=1 -DLLFIO_HEADERS_ONLY=0 -DOUTCOME_USE_SYSTEM_STATUS_CODE=1 -DQUICKCPPLIB_ENABLE_VALGRIND=1 -imsvcbuild\x64-windows-clang\vcpkg_installed\x64-windows-static\include /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MTd -std:c++20 /showIncludes  -c -- mcve.cpp
`

**Expected behavior**
No compiler error.

**Environment**
 - OS: Windows 10
 - Compiler: Clang 15.0.1 (applies to older versions too) with MSVC-like command-line
 - Project Version: f8d2eebeb1742a5ebec4da856d47ba6fd1a48a8c

**Additional context**
I'm unsure what the preferred fix would be:
* Remove the `…_FUNC_SPEC` macro from the friend declaration (l. 157)
* Add a companion macro for `…_FUNC_SPEC` to support friend declarations (i.e. `…_FUNC_SPEC` without `extern`).

There is one additional occurence:
https://github.com/ned14/llfio/blob/f8d2eebeb1742a5ebec4da856d47ba6fd1a48a8c/include/llfio/v2.0/detail/impl/posix/test/io_uring_multiplexer.ipp#L100

**Comment by ned14** [comment]
Sorry about writing failing code :)

The fix should be easy, declare the function before the friend declaration so it gets the `LLFIO_HEADERS_ONLY_FUNC_SPEC`, then the friend declaration probably can make do without it. I say "probably" because other compilers may complain if the friend declaration doesn't exactly match the earlier declaration.

Currently at a WG21 meeting in person so time is limited.

**Comment by BurningEnlightenment** [comment]
> The fix should be easy, declare the function before the friend declaration so it gets the `LLFIO_HEADERS_ONLY_FUNC_SPEC`, then the friend declaration probably can make do without it. 

Luckily that declaration already exists at an approppriate place :)

> I say "probably" because other compilers may complain if the friend declaration doesn't exactly match the earlier declaration.

That thought kept me from just commit a fix. However, I will just go ahead and prepare a PR.

> Currently at a WG21 meeting in person so time is limited.

No worries, `clang-cl` isn't a primary target platform for me. I've actually procrastinated reporting this for a year or two 😅. So delaying by a week or two doesn't really matter.

Godspeed to you and your proposals.
