### ISSUE TITLE
Wrong link in readme

### ISSUE THREAD

**Issue by ngrodzitski** [ned14/llfio#119]
I believe it is a wrong link here (p2596 instead of p2586):
https://github.com/ned14/llfio/blob/583f838bf7fa5a18a521ad040ffafbb574383b52/Readme.md?plain=1#L26C1-L26C1

**Comment by BurningEnlightenment** [comment]
Indeed. However, IIRC @ned14 won't pursue p2586 any further, i.e. the proposal is dead which we should either mention this or just remove the line completely.
