### ISSUE TITLE
How to set the share mode?

### ISSUE THREAD

**Issue by jamboree** [ned14/llfio#12]
I'm playing with LLFIO to implement a toy HTTP downloader, it works, but I'm surprised that I can delete the file during downloading.

It's opened this way:
```c++
                auto file = fio::async_file(io, {}, filename.native(),
                    fio::io_handle::mode::write,
                    fio::io_handle::creation::if_needed,
                    fio::io_handle::caching::all).value();
```
Is there a way to set the share mode when opening the file?

**Comment by ned14** [comment]
There is not. POSIX has no such thing as share mode, so neither does LLFIO.

What you'd do on POSIX is create an anonymous inode using `temp_inode()`, fill it with data, and only once complete you'd hard link it to the location you want. However I haven't implemented `link()` yet.

Would you like me to implement `link()` for you? A window should arise next week.

**Comment by jamboree** [comment]
I'm on Windows. I was referring to the `dwShareMode` param described [here](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew#parameters). 
I want to disable FILE_SHARE_DELETE.

Not familiar with POSIX api. What does POSIX do in the given example? Does it allow the user to delete/rename the file while another process is still writing to it?

**Comment by ned14** [comment]
Oh yes, POSIX lets you not just delete or rename an open file, but to arbitrarily permute the paths of lots of open files by renaming a parent directory. That's totally permitted and introduces lots of fun race conditions.

You have two choices. One is you can create the file yourself with file share delete disabled, and pass the HANDLE to LLFIO to manage. There is a constructor for that. Or you can use the `temp_inode()` pattern I described earlier, though you'll be stuck waiting for me to implement `link()` next week. Which would you prefer?

**Comment by ned14** [comment]
Closing due to staleness.
