### ISSUE TITLE
Linux Minimal Kernel Version Support 

### ISSUE THREAD

**Issue by eyalgolan1337** [ned14/llfio#122]
In the readme documentation it is mentioned that the library tries it's best effort to support Linux kernel version 2.6.32.
I was wondering if that is because that is what library is tested on or because there are other limitations preventing the library from supporting even older kernels.
Is there a list of required Linux features that one can check against for support?
My specific requirement is 2.6.18, not that far from 2.6.32 but still.

**Comment by ned14** [comment]
It is due to RHEL6.

You've got a good chance it will work on slightly older Linux kernels. Your bigger problem will be bugs in the Linux filesystems of such ancient kernels. I wouldn't use XFS in a 2.6 kernel, for example.
