### ISSUE TITLE
Please be more explicit with this error message

### ISSUE THREAD

**Issue by assarbad** [ned14/llfio#13]
```
FATAL: You must set a binary directory that is different from your source directory.
       You might consider D:/llfio/build or D:/llfio-build
```

... originating from:

```
message("FATAL: You must set a binary directory that is different from your source directory.")
message("       You might consider ${CMAKE_SOURCE_DIR}/build or ${_parent}/${_leaf}-build")
```

The solution to this is very unobvious (or perhaps it is, if you're working with CMake on a daily basis which I am not).

I first tried setting `CMAKE_INSTALL_PREFIX` and looking if any cache existed (which it did not), so reran and got the same error.

Only after searching the whole folder for the first line of the error message *I thought* I had figured out that apparently `CMAKE_BINARY_DIR` should be set to one of the suggested values. Alas, that one also didn't work. I no longer have an idea what exactly I am supposed to set there.

But I am not sure if this is an issue of this project or some other project. So first filing it here.

Thanks for reading and thanks for bringing the world this library, Niall!

With best regards,

Oliver

**Comment by assarbad** [comment]
Found a remedy. I had to create a build directory, change into that and invoke `cmake` in a fashion that simply referred to the source directory.

**Comment by ned14** [comment]
Sorry! As you have noticed, I have not invested the effort in making the library user friendly. And I have been surprised at the number of people using it. I need to fix this, and this ticket will make me improve things.

BTW are you aware the library is header only, and thus you need not have bothered with cmake at all?

**Comment by assarbad** [comment]
Hi @ned14 , yes I figured, but I failed to build the single header version for some reason and it wasn't in the archives either.

Thanks for creating the library and sharing it with us!

Oliver

PS: And just to make sure (because communication over TCP/IP tends to foster misunderstandings), I didn't want to come off rude. It just seemed counter-intuitive.

**Comment by ned14** [comment]
The single header edition doesn't work yet, I haven't got round to finishing debugging it.

But the library is header only. Just include and go, no build step needed.

I've had more feedback (e.g. #14) that LLFIO now needs a proper install and build docs page.

**Comment by ned14** [comment]
Ok, please give https://github.com/ned14/llfio/blob/develop/Build.md a view and see if it works for you.

**Comment by assarbad** [comment]
Awesome, will give these instructions a try now and get back to you. If I feel something is missing or unclear I will send a pull request ASAP.

**Comment by assarbad** [comment]
Got the following error, but I simply removed the respective `case` when trying to build and then it worked fine (couldn't be bothered to investigate if this was an issue because of the submodules having diverged from this code or whatever ...):

```
1>d:\llfio\include\llfio\v2.0\detail\impl\windows\storage_profile.ipp(305): error C2065: 'BusTypeSCM': undeclared identifier
1>d:\llfio\include\llfio\v2.0\detail\impl\windows\storage_profile.ipp(305): error C2051: case expression not constant
```

Affected `case` in `storage_profile.ipp` (the `enum` doesn't contain this name):

          case BusTypeSCM:
              sp.controller_type.value = "Storage Class Memory";
              break;

I would also recommend to add, perhaps, a paragraph on these warnings here:

```
1>CL : warning : LLFIO_HEADERS_ONLY=1, LLFIO_EXPERIMENTAL_STATUS_CODE=0 and NTKERNEL_ERROR_CATEGORY_INLINE=1 on Windows, this can produce unreliable binaries where semantic comparisons of error codes randomly fail!
1>CL : warning : Defining custom error code category ntkernel_category() via header only form is unreliable! Semantic comparisons will break! Define NTKERNEL_ERROR_CATEGORY_INLINE to 0 and only ever link in ntkernel_category() from a prebuilt shared library to avoid this problem.
```

I certainly found them confusing together with your statement that LLFIO is meant to work as header-only.

Thanks and best regards,

Oliver

**Comment by assarbad** [comment]
Just created a pull request. It doesn't contain the paragraph I was recommending in my previous comment, since I don't feel qualified to make statements about these warnings.

I think _this_ can be closed, right?

**Comment by ned14** [comment]
I added some explanation of the build warnings when in header only build on Windows. Thanks for the feedback!
