### ISSUE TITLE
Padding/aligning a memory mapped file to a specific byte boundary

### ISSUE THREAD

**Issue by Arastais** [ned14/llfio#130]
Hi there; Thanks for your great work on this library.

I wanted to get some clarification on if it's possible to align and/or pad a given `llfio::memory_mapped_file` to a specific (e.g. 16-byte, 32-byte, etc.) boundary, especially such that accessing that many bytes of data at a time won't exceed the maximum extent of the mapped memory.  I don't see any example or clear indication of being able to do so in llfio's documentation, and along with my understanding of memory mapping, **I would assume the answer is no**. I realize that there's `reserve()` and `truncate()` for padding but that seems to resemble the standard library's `reserve()` for containers (e.g. `std::vector`), meaning like with std containers, I can't immediately read from the newly reserved memory. I realize that the naive solution is to copy the entire mapped memory into an aligned/padded container, but I would think that doing so at least partially defeats the purpose of mapping files to memory.

I do however see `file_handle::requires_aligned_io()` and the `align all i/o to 4Kb boundaries for this to work.` comment in the `llfio::handle::caching` flags; This to me implies that there must be someway to "manually" align the handle (i.e. the mapped memory) yet I see no such documentation, example, etc. highlighting said implication.

My main use case for this is SIMD, specifically using vectorized instructions to read/write (including copy) from a memory mapped file, preferably with an aligned load/store (after aligning the mapped memory to the required byte boundary for it, of course). However, I'm sure this feature has many other use cases as well. But again, I don't see how it's even possible to pad the data so that at least an unaligned load can be used.

**Comment by ned14** [comment]
> I would assume the answer is no

You are correct. The system determines where memory mapped files will go, and on all major systems 4Kb in RAM has the same alignment as its 4Kb in the file so the page fault implementation is simple and fast. If you happen to store your SIMD vectors unaligned within the file, they will be unaligned in memory.

On a post-Haswell Intel CPU I wouldn't worry about unaligned SIMD. Apart from the odd extra cycle of stall, it performs well. Some very recent AArch64 CPUs are similar. For everything else, you really should make sure the contents of the file are correctly aligned for SIMD.

Re: aligned i/o, this refers to files opened with the kernel cache disabled. You shouldn't memory map such files, performance is terrible. If the kernel cache is disabled for a file, if the code is to be portable all i/o to and from it must be in 4Kb multiples from buffers also aligned to 4Kb. This is what the documentation is referring to.

**Comment by ned14** [comment]
Strictly speaking, reading anything off the end of a map could segfault. In practice, you'll find the system rounds up to the next nearest page size, which is 4Kb for most systems. It _may_ fill the end with zeros, but this isn't guaranteed, and I have seen garbage in there sometimes.

What I'd do is have my SIMD code unrolled and processing large chunks at a time until it gets towards the end of the map, then it would drop down to not unrolled code and consuming smaller chunks. If your text file just happens to be exactly a multiple of 4Kb long, then reading just off the end of the map may segfault. Windows and other systems tend to be strict there, Linux less strict.

I normally would recommend `signal_guard` at this point as a lightweight way of recovering from segfaults, but it is known to be broken on recent glibc's and until I fix it, I can't recommend its use. It does work 99.99% of the time on new glibcs, but not 100%.

**Comment by Arastais** [comment]
> What I'd do is have my SIMD code unrolled and processing large chunks at a time until it gets towards the end of the map, then it would drop down to not unrolled code and consuming smaller chunks.

That's what I was doing originally, but wanted to know if you thought there was a way to do it without dropping down. Thanks for your input; Your help is greatly appreciated.

With that information in mind, as a final note, if I wanted to copy the entire data buffer, do you think would it be better to use SIMD to copy the entire mapped memory or use `clone()` on the handle and then use the clone's buffer? 

A more specific and practical example use case is that I need to pass the file contents to a C API function that `free`s the passed buffer after reading and processing the data (i.e. once it's done); This means that I (presumably) can't just pass `mh.address()` to it, I need to copy the data first then pass the copied memory as the buffer.

**Comment by ned14** [comment]
> With that information in mind, as a final note, if I wanted to copy the entire data buffer, do you think would it be better to use SIMD to copy the entire mapped memory or use clone() on the handle and then use the clone's buffer?

`clone()` only clones the handle, not the contents. If you want to clone the contents, use `clone_extents_to()`.

If your filing system supports cheap extents cloning, you can clone any size of file in about 150 milliseconds. If copying memory would be faster than that, do that instead, if it would be slower, use extents cloning.

Also look into copy on write memory maps, they get under utilised for when you need to not modify the underlying file.

> A more specific and practical example use case is that I need to pass the file contents to a C API function that frees the passed buffer after reading and processing the data (i.e. once it's done); This means that I (presumably) can't just pass mh.address() to it, I need to copy the data first then pass the copied memory as the buffer.

I am afraid so. C APIs often force memory copying because they insist on calling `free()` on what you supply them.

**Comment by Arastais** [comment]
> `clone()` only clones the handle, not the contents. If you want to clone the contents, use `clone_extents_to()`.

Thanks for the reminder, completely forgot about `clone_extents_to()`

</br>

> Also look into copy on write memory maps, they get under utilised for when you need to not modify the underlying file.

Where could I find more documentation/information on this, particularly with llfio? Other than  `clone_extents_to()`, I couldn't find anything under `llfio::mapped_file_handle`'s doxygen or P1883R2.

**Comment by ned14** [comment]
> Where could I find more documentation/information on this, particularly with llfio?

https://pubs.opengroup.org/onlinepubs/009604499/functions/mmap.html

> MAP_SHARED and MAP_PRIVATE describe the disposition of write references to the memory object. If MAP_SHARED is specified, write references shall change the underlying object. If MAP_PRIVATE is specified, modifications to the mapped data by the calling process shall be visible only to the calling process and shall not change the underlying object. It is unspecified whether modifications to the underlying object done after the MAP_PRIVATE mapping is established are visible through the MAP_PRIVATE mapping. Either MAP_SHARED or MAP_PRIVATE can be specified, but not both.

You can create a copy on write map of a file in LLFIO using `section_handle::flag::cow` https://github.com/ned14/llfio/blob/develop/include/llfio/v2.0/map_handle.hpp#L62
