### ISSUE TITLE
`render` functions do not match P1030R6 

### ISSUE THREAD

**Issue by sneves** [ned14/llfio#139]
In [P1030R5](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1030r5.pdf) the render functions were named `render_zero_terminated`/`render_not_zero_terminated` and took an additional `path_view_component` as first argument.

In [P1030R6](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p1030r6.pdf) the names were changed to `render_null_terminated`/`render_unterminated` and the unnecessary first argument was removed.

[This commit](https://github.com/ned14/llfio/commit/938b8456e9d575c4455ddeca5fbe808c040b8c88) changed the names to the P1030R6 convention, however it left the first argument there.

**Comment by BurningEnlightenment** [comment]
I'll take a shot at this later today as its an obvious oversight from the transition free function => member function. I guess I'll also add the `const` qualifications proposed for R7.
