### ISSUE TITLE
Question about case when fsync() fails to flush data

### ISSUE THREAD

**Issue by maksqwe** [ned14/llfio#17]
Hi Niall!

I see that you use `fsync()` in the libbrary code and thefore I have a question.
I recently read about a problem encountered by PostgreSQL devs connected with using fsync().

TLDR: They were retrying `fsync()` call after first one was failed. There is an issue because second fsync() does not flush prev data.

There is LWN link: https://lwn.net/Articles/752063/

I'll just copy small quote:

> Craig Ringer first reported the problem to the pgsql-hackers mailing list at the end of March. In short, PostgreSQL assumes that a successful call to fsync() indicates that all data written since the last successful call made it safely to persistent storage. But that is not what the kernel actually does. When a buffered I/O write fails due to a hardware-level error, filesystems will respond differently, but that behavior usually includes discarding the data in the affected pages and marking them as being clean. So a read of the blocks that were just written will likely return something other than the data that was written. 

There were several solutions about error reporting for such situation in the Linux kernel starting from 4.13.

As I saw for the workaround could be used `disable_safety_fsyncs` flag.
Do you have some suggestions about how to avoid such situation with llfio in the another way?

P.S. Some related links:
https://wiki.postgresql.org/wiki/Fsync_Errors
https://docs.google.com/presentation/d/1D6wTVgLK701CDzUJ3iwcnp5tVwbSlzCd5aPJAdLbq8Q/edit#slide=id.p

**Comment by ned14** [comment]
As you'll see in the docs at https://ned14.github.io/llfio/classllfio__v2__xxx_1_1io__handle.html#aa3ec366f663f85fb4d679542b8c1b41a, nobody should assume `fsync()` is not a no-op. It's permitted by POSIX to be a no-op, and is a no-op on many common server configurations.

We still go through the motions though, as you point out, unless `disable_safety_fsyncs` is set. This is to try and force some consistency between filing systems e.g. some have delayed update of the directory inode with a new file, but others do not. But that's the purpose of those safety fsyncs, it's all about *metadata* between filing systems. If you check, you should notice we fsync the parent directory on Linux for example.

The way to avoid fsync problems is to not use fsync! Disabling caching is probably much more portable and reliable. But even then, ideally design your filesystem algorithm so random reordered writes aren't fatal, if you care about your data.
