### ISSUE TITLE
Name clash of __cpuid lambda with macro from cpuid.h 

### ISSUE THREAD

**Issue by ntrifunovic** [ned14/llfio#18]
In header file [`cpuid.h`](https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/cpuid.h#L187) macro `__cpuid` is defined.

In [include/llfio/v2.0/detail/impl/posix/storage_profile.ipp#L162](https://github.com/ned14/llfio/blob/master/include/llfio/v2.0/detail/impl/posix/storage_profile.ipp#L162) there is lambda function also named `__cpuid`:
```cpp
 auto __cpuid = [](int *cpuInfo, int func) { __asm__ __volatile__("cpuid\n\t" : "=a"(cpuInfo[0]), "=b"(cpuInfo[1]), "=c"(cpuInfo[2]), "=d"(cpuInfo[3]) : "0"(func)); };  // NOLINT
````

If program includes both `cpuid.h` and llfio compilation would fail.

**Comment by ned14** [comment]
Bah. Fair enough, I'll fix it.

**Comment by ned14** [comment]
Done. Thanks for the BR!
