### ISSUE TITLE
misguided MSVC C2760 in /permissive- mode

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/llfio#24]
A detail in the type erasure pattern used for the completion handlers in `async_file_handle.hpp` ([1](https://github.com/ned14/llfio/blob/develop/include/llfio/v2.0/async_file_handle.hpp#L385), [2](https://github.com/ned14/llfio/blob/develop/include/llfio/v2.0/async_file_handle.hpp#L440) and [3](https://github.com/ned14/llfio/blob/develop/include/llfio/v2.0/async_file_handle.hpp#L483)) confuses MSVC when `/permissive-` is enabled.

I reduced the issue to a minimal repro ([godbolt](https://godbolt.org/z/k9oQCQ)). The explicit constructor seems to be the triggering detail -- removing the `explicit` keyword makes MSVC happy again. I will file an issue in the MS developer community as soon as I have a better title idea than "compiler bug".

(Also note that the compiler errors even if the template function is not instantiated)

**Comment by ned14** [comment]
Sigh. Outcome triggered a similar bug in MSVC. As this is an internal implementation detail, we can probably make an exception for MSVC. Thanks for the bug report.

**Comment by ned14** [comment]
Fixed!
