### ISSUE TITLE
`const_buffer_type barrier(const_buffer_type req, bool evict = false)` missing in `mapped_file_handle`

### ISSUE THREAD

**Issue by ntrifunovic** [ned14/llfio#33]
Function `const_buffer_type barrier(const_buffer_type req, bool evict = false)` is present in `map_handle`, but missing in `mapped_file_handle`.

In my use case, I have memory-mapped files living on NVRAM storage for which I would like to use this barrier. Having it in `mapped_file_handle` would be nice :smiley:

**Comment by ntrifunovic** [comment]
I figured out now that `const_buffer_type barrier(const_buffer_type req, bool evict = false)` is static member function of `map_handle` so I can call it.

**Comment by ned14** [comment]
I'm minded that `mapped_file_handle` should expose NVM `barrier()` too, so reopening.

**Comment by ntrifunovic** [comment]
An alternative would be to make `barrier` a free function, but I am not sure what would be the best header for it to live in as a free function :smiley:

**Comment by ned14** [comment]
Made into a free function. Thanks for the suggestion.
