### ISSUE TITLE
Preprocessor guard typo

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/llfio#42]
https://github.com/ned14/llfio/blob/7747eb23bb3afef66d322b6999cf0809dc36dfe7/include/llfio/v2.0/path_view.hpp#L48

Wild guess: it should be `__cplusplus <= 201703` in the conjunctive clang clause -- clang doesn't define char8_t in C++17 mode 😅

**Comment by ned14** [comment]
clang tells lies about when it supports `char8_t` and when it does not. But setting that aside, I say you are likely right.

**Comment by DBJDBJ** [comment]
C 2.X will "fix" char8_t mess, in C++2a it is "just" a keyword. It will be done by 2023, no worries.

**Comment by ned14** [comment]
Thanks to #50, we think we finally have a correct fix for this. Thanks to everybody for their help.
