### ISSUE TITLE
Decoupling LLFIO from UNICODE/_UNICODE

### ISSUE THREAD

**Issue by gix** [ned14/llfio#44]
LLFIO currently requires (and enforces) the presence of `_UNICODE` which makes it impossible to use in legacy and similar applications that cannot define `_UNICODE` yet.

Looking through the source I see no reason to require this. Most code paths use `wchar_t` explicitly, and thus should call the W-prefixed versions of Win32 functions instead of the `_UNICODE` controlled macros. Only `SE_LOCK_MEMORY_NAME` has to be replaced with a string (as is already done for other `LookupPrivilegeValue` calls). With these few changes LLFIO is indifferent to whether it is used in an ANSI or UNICODE context.

The blanket `all_compile_definitions(PUBLIC _UNICODE UNICODE)` in `quickcpplib` must be changed, or maybe even removed (`outcome` and `status-code` don't need it anyway). Not sure how you'd like this resolved. For the rest I'll gladly provide patches.

**Comment by ned14** [comment]
You're nuts wanting `_UNICODE` agnosticism, but I too have worked in places where ANSI codebases were in use. I send my commisserations.

`_UNICODE` also changes quite a few other bits than the Win32 APIs. I wouldn't do the work myself, but if you raise a PR against each of the libraries involved, I'll be happy to review those and merge as needed.

**Comment by ned14** [comment]
In theory, should now be working. Let me know if it isn't. Thanks for the PRs!
