### ISSUE TITLE
char8_t emulation on clang-9

### ISSUE THREAD

**Issue by cstratopoulos** [ned14/llfio#49]
Hello!

Just ran into what seems like an awkward intersection of case/version checking when using clang-9 and libcxx. Judging by https://github.com/ned14/llfio/commit/5cceb1a49dce9d6daf619890c888ed3c10f48816 this has already been a bit of a headache and looks like it may continue to be one. 

This snippet should illustrate the main points of the issue
https://godbolt.org/z/eGFK7d
- `__cplusplus` still corresponds to C++17 when `-std=c++2a` is passed (N.B.: `-std=c++20` is as yet unsupported, maybe they're waiting til then to bump `__cplusplus`)
- `__CHAR8_TYPE__` does not ever appear to be defined, although `__cpp_char8_t` is, and vexingly,
- `fno-char8_t` is recognized at the command line but only changes whether `__cpp_char8_t` is defined, not whether you can in fact define a `char8_t` in your code. 

This creates a bit of a mess and may require more than just `LLFIO_PATH_VIEW_CHAR8_TYPE_EMULATED` I fear. To expand a bit, due to the `__CHAR8_TYPE__`/`__cplusplus` thing outlined above, LLFIO deduces it needs to emulate `char8_t` with clang-9, making `struct char8_t` an illegal definition. Correct deduction of `LLFIO_PATH_VIEW_CHAR8_TYPE_EMULATED` can be obtained by checking for `__cpp_char8_t` as well though:
```diff
-     || (defined(__clang__) && !defined(__CHAR8_TYPE__) && (__cplusplus < 202000L || __clang_major__ < 9))
+     || (defined(__clang__) && (!defined(__CHAR8_TYPE__) && !defined(__cpp_char8_t)) && (__cplusplus < 202000L || __clang_major__ < 9))
```

The next issue, then, is that `LLFIO_PATH_VIEW_CHAR8_TYPE_EMULATED` is used to dispatch `llfio::detail::_codecvt`, and to determine if an invalid conversion has been requested for clang with libc++. [Clang C++ status](https://clang.llvm.org/cxx_status.html) reports support for `char8_t` but the paper they link mentions `codecvt` specializations for `char8_t` and, for clang-9/libc++ at least, you'll find no mention of `char8_t` in any header to do with `codecvt`. 

For my local tests I did the stupid workaround of
```diff
   wchar_t *reencode_path_to(size_t &toallocate, wchar_t *dest_buffer, size_t dest_buffer_length, const char8_t *src_buffer, size_t src_buffer_length)
   {
-#if LLFIO_PATH_VIEW_CHAR8_TYPE_EMULATED
+#if 1 //LLFIO_PATH_VIEW_CHAR8_TYPE_EMULATED
 #if defined(_LIBCPP_VERSION)
```
With this I was successfully able to build `llfio_sl` for clang-9/libc++. 

However I wonder if it might be necessary to fix `detail::_codecvt` in some cases too. Right now we have a full specialization for the fallthrough
```cpp
  template <> struct _codecvt<char8_t, char> : std::codecvt<char, char, std::mbstate_t> { 
```
but this is only `#if LLFIO_PATH_VIEW_CHAR8_TYPE_EMULATED`. I think it might be necessary instead to do a partial specialization along the lines of 
```cpp
template<typename ExternT> struct _codecvt<char8_t, ExternT> : std::codecvt<char, ExternT, std::mbstate_t> {
```
to handle clang-9 libc++ having no `codecvt` specializations for `char8_t`. I _think_ this is valid as per [p0482](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0482r5.html) which proposes

> New char8_t based specializations of codecvt and codecvt_byname for converting between UTF-16, UTF-32, and UTF-8. The existing char based specializations are deprecated. The new specializations are functionally identical to the deprecated ones.

**Comment by ned14** [comment]
This is great work, thank you. To be honest I keep accepting patches which "fix" this, and they only seem to redistribute the problem. For me personally, I just use C++ 17, and there there is no problem, however that is obviously not a long term sustainable solution.

Let me review this in more detail next week, and I'll get back to you then. Thanks for taking the time to send this in.

**Comment by ned14** [comment]
For the `char8_t` to `wchar_t` `reencode_path_to()` fix, can you check if that works for you? I regularly use clang, but not with libc++, as is probably obvious.

**Comment by DBJDBJ** [comment]
One very complex story indeed, showing the inability of WG21 to serve its purpose. In danger of sounding young (laugh) I might repeat what is by now obvious: [char8_t is broken](https://github.com/sg16-unicode/sg16/issues/58) ... 

Ok, let's be helpful. One detail is very useful to watch as the sure sign  things are moving with `char8_t` implementation. The availability of[ fully implemented](https://en.cppreference.com/w/cpp/header/cuchar)  C++20 `<cuchar>` .. in all 3 of them compilers that is. You just have to believe me :)

**Comment by cstratopoulos** [comment]
Hey just took a look at this. I tried to build for clang9/libc++ against e07bc79 and removed my patch workaround. Unfortunately now the compiler complains that 
```
_deps/llfio-src/src/../include/llfio/v2.0/detail/impl/path_view.ipp:38:61: error: implicit instantiation of undefined template 'std::__1::codecvt<char, wchar_t, __mbstate_t>'
  template <class InternT, class ExternT> struct _codecvt : std::codecvt<InternT, ExternT, std::mbstate_t>
```
I poked around in the header with the `codecvt` specializations defined, and it seems that sure enough they only define `codecvt<wchar_t, char, ...>` but not the other way around. I saw

>      // libc++ appears to be missing char8_t to wchar_t codecvt entirely 

and it seems they may be missing _anything_ to `wchar_t` entirely

**Comment by ned14** [comment]
Ok, looks like I'll need to go do a build with libc++ so and come up with something which works. Thanks for your patience.

**Comment by ned14** [comment]
Fixed!
