### ISSUE TITLE
Compile error for Apple implementation of pipe_handle::pipe

### ISSUE THREAD

**Issue by cstratopoulos** [ned14/llfio#54]
Hello!

Saw that OSX CI/precompiled binaries appear to be disabled "pending XCode filesystem support". Was just running a local OSX build using homebrew clang++-9 with libc++ and got a compile error in `impl/posix/pipe_handle.ipp`. Figure I'd just include a patch rather than a PR as it's a one-liner but you may want to handle it differently:
```diff
diff --git a/include/llfio/v2.0/detail/impl/posix/pipe_handle.ipp b/include/llfio/v2.0/detail/impl/posix/pipe_handle.ipp
index 321c801e..aafd1fe5 100644
--- a/include/llfio/v2.0/detail/impl/posix/pipe_handle.ipp
+++ b/include/llfio/v2.0/detail/impl/posix/pipe_handle.ipp
@@ -105,7 +105,7 @@ result<pipe_handle> pipe_handle::pipe(pipe_handle::path_view_type path, pipe_han
 #ifdef __APPLE__
     native_handle_type dirhfd_;
     dirhfd_.fd = dirhfd;
-    path_handle dirhfdwrap(dirhfd_);
+    path_handle dirhfdwrap((handle(dirhfd_)));
     auto dirhpath = dirhfdwrap.current_path();
     dirhfdwrap.release();
     OUTCOME_TRY(dirhpath);
```

Without this there is no match for constructing `path_handle` from `native_handle_type`, but this looked like the closest match I could spot (i.e., invoke the `explicit handle(native_handle_type)` ctor), or else `path_handle dirhfdwrap(dirhfd_, {}, {})` which would invoke the same as above. 

Anyway you maybe happy to hear that change was enough for a clean build of SL/DL with the configuration above

**Comment by ned14** [comment]
Fixed! Thanks for reporting it!
