### ISSUE TITLE
Clarify supported Windows versions

### ISSUE THREAD

**Issue by gix** [ned14/llfio#55]
I couldn't find this anywhere in the documentation. What is the supported minimum version of Windows?

I'm asking primarily because `NtFlushBuffersFileEx` is not available on Windows 7 and whether I should work around this myself or not.

**Comment by ned14** [comment]
We track Windows EOL. Windows 7 EOLed Jan 14th 2020.

That said, if you sent in a PR which falls back to `NtFlushBuffersFile` if `NtFlushBuffersFileEx` isn't there, I would merge it.

**Comment by ned14** [comment]
Added a supported OS kernel version statement to docs, closing.
