### ISSUE TITLE
Outcome traits/type aliases for io_handle::result

### ISSUE THREAD

**Issue by cstratopoulos** [ned14/llfio#56]
Hey again

Minor nit I ran into trying to write some generic helper functions for working with `basic_result<...>`--the idea is I tried to write a constrained function template that looked like

```cpp
template<
    class Result,
    std::enable_if_t<outcome::is_basic_result_v<Result>, int> = 0>
my_return_type<typename Result::value_type>
function(Result&&);
```

This mostly worked fine when dealing with LLFIO and other `result`-returning functions, but failed when trying to wrap a call to `llfio::read` as the return type there is `io_handle::io_result` which inherits `basic_result`. 

If this is not an intentional ommission, maybe we could do 

```
template<class T>
struct outcome::is_basic_result<io_handle::io_result<T>> :
    outcome::is_basic_result<typename io_handle::io_result<T>::Base> {};
```

However with the above, my function would run into another substitution failure trying to name `Result::value_type`, so maybe we could also give `io_handle::io_result` its base class typedefs? e.g.,, `using value_type = typename Base::value_type`, etc. 

Alternatively, it occurred to me while writing this that the `ValueOrError` concept might be a better fit for the job. And the code above works with `ValueOrError<Result>` as the constraint instead. However `ValueOrError` doesn't guarantee the `assume_`-flavoured member functions, which I am using in my function, and I still have to get `value_type` with some `decltype`ing

**Comment by ned14** [comment]
I've added new Concepts to Outcome for your use case: https://ned14.github.io/outcome/reference/concepts/basic_result/

Let me know how they go for you.

**Comment by cstratopoulos** [comment]
Just tested this out, looks good on my end so I'll mark this closed unless you want to do anything further on it!
