### ISSUE TITLE
Niall. I am going to support LLFIO. 

### ISSUE THREAD

**Issue by expnkx** [ned14/llfio#59]
This proves my scatter_output_stream concept can eliminate all costs for scatter stream. No heap allocation. No extra copy. It works without heap, libc and main function (freestanding environment). I think for mapped files if you expose enough interfaces, it should perform it as a buffer_output_stream just like std::streambuf.

https://github.com/expnkx/fast_io/blob/master/testsuites/0005.freestanding/0002.println/helloworld_linux_writev_floating_point.cc
https://github.com/expnkx/fast_io/blob/master/testsuites/0005.freestanding/0002.println/helloworld_linux_writev_floating_point.s

https://github.com/expnkx/fast_io/blob/680ae248832f87a86c624ffa5537fbfcaa0ebeac/include/fast_io_concept.h#L189

Unfortunately, I could not compile your code and I do not know which part should be optimized and which part should not.

![image](https://user-images.githubusercontent.com/57303909/85955605-b21bad00-b94d-11ea-9076-f6b08737743d.png)

**Comment by ned14** [comment]
You can twiddle the version check at https://github.com/ned14/quickcpplib/blob/master/include/quickcpplib/detach_cast.hpp#L37, use an earlier GCC, or use a non-broken compiler such as clang.

**Comment by expnkx** [comment]
> You can twiddle the version check at https://github.com/ned14/quickcpplib/blob/master/include/quickcpplib/detach_cast.hpp#L37, use an earlier GCC, or use a non-broken compiler such as clang.

Well, clang is also very broken for its poor concepts support.

**Comment by ned14** [comment]
GCC is by far the most problematic compiler for me, both personally and at work. Quality there is not what it once was. GCC 10 was particularly bad, even compared to usual.

I can't fix the version check until GCC 11 releases, because Outcome is used by some of the GCC devs when validating a new GCC major release, same as for MSVC or clang major releases. So I specifically need to ensure that conformance stuff fails until they've decided, yet again, to kick the many GCC ICEs and problems down the road again. Once GCC 11 releases, I'll bump all the version checks which still fail.

**Comment by expnkx** [comment]
> GCC is by far the most problematic compiler for me, both personally and at work. Quality there is not what it once was. GCC 10 was particularly bad, even compared to usual.
> 
> I can't fix the version check until GCC 11 releases, because Outcome is used by some of the GCC devs when validating a new GCC major release, same as for MSVC or clang major releases. So I specifically need to ensure that conformance stuff fails until they've decided, yet again, to kick the many GCC ICEs and problems down the road again. Once GCC 11 releases, I'll bump all the version checks which still fail.

Ok. When you've done that, feel free to tell me and i will support it by then.

**Comment by ned14** [comment]
GCC 11 is scheduled for release in Q2 2021.
