### ISSUE TITLE
Binary links are dead.

### ISSUE THREAD

**Issue by doctor-claw** [ned14/llfio#60]
Download links are broken for `llfio-v2.0-binaries-win64-latest.zip` and `llfio-v2.0-binaries-linux64-latest.tgz`:

```
Index of /static/files/
../
boost.outcome/                                     11-May-2017 15:50                   -
llfio/                                             02-Jul-2020 23:00                   -
other/                                             11-Jul-2019 20:30                   -
outcome/                                           22-Jun-2020 23:00                   -
upload/                                            18-Sep-2019 23:04                   -
boost.outcome-v1.0-source-latest.tar.xz            11-May-2017 15:50             1075620
llfio-v2.0-binaries-linux64-latest.tgz             18-Sep-2019 23:04                  78
llfio-v2.0-binaries-win64-latest.zip               18-Sep-2019 23:04                  76
llfio-v2.0-source-latest.tar.xz                    02-Jul-2020 23:04            52981904
outcome-v2.0-source-latest.tar.xz                  22-Jun-2020 23:01            14831504
```

**Comment by ned14** [comment]
That is surprising. Thanks for reporting it.

**Comment by ned14** [comment]
So, turns out there is a simple cause, and that is that LLFIO has not passed all its unit tests on Travis nor Appveyor for many months. Hence no precompiled binaries have been generated.

**Comment by doctor-claw** [comment]
Aha, good news that the cause is straightforward - is the fix equally straightforward ?

**Comment by ned14** [comment]
Well, the failures on travis are due to travis. I just injected a bunch of debug printing there, because I have no idea why it would fail. The failures on appveyor are also due to appveyor, and I just pushed some workarounds. So we'll let those cycle, and see what pops out.

**Comment by ned14** [comment]
I should also mention that LLFIO is heavily used by work code on both Linux and Windows. It gets battered every day there, and has been for months. So it's definitely working well ATM.

**Comment by doctor-claw** [comment]
I was just after the fastest way to get going with it, to try it out and see if it's appropriate for my use case :-)

**Comment by ned14** [comment]
https://github.com/ned14/llfio/blob/master/Build.md is surely no more than 15 minutes of your time, total.

**Comment by doctor-claw** [comment]
I'm on it ;-)

**Comment by ned14** [comment]
https://dedi5.nedprod.com/static/files/ now contains valid Linux and Windows prebuilt binaries. Mac OS ones still work in progress.
