### ISSUE TITLE
Required kernel version

### ISSUE THREAD

**Issue by zpyatt** [ned14/llfio#62]
I'm trying to upgrade to the latest llfio, after sorting out the dependency hell, I think I've got everything set up correctly, but it fails to build with my Linux kernel (~3.10 I think). The problem is in **llfio/include/llfio/v2.0/detail/impl/posix/file_handle.ipp** line# **744**. In the function ```file_handle::clone_extents_to ```:
```cpp
    auto _copy_file_range = [&](int infd, off_t *inoffp, int outfd, off_t *outoffp, size_t len, unsigned int flags) -> ssize_t {
#if defined(__linux__)
      return copy_file_range(infd, inoffp, outfd, outoffp, len, flags);
#elif defined(__FreeBSD__)
      // This gets implemented in FreeBSD 13. See https://reviews.freebsd.org/D20584
      return syscall(569 /*copy_file_range*/, intfd, inoffp, outfd, outoffp, len, flags);
#else
```
If we are using linux it makes a call to **copy_file_range** which apparently requires a 4.5 kernel or higher. I changed it to use **sendfile**, but I'm unsure what offset value to use, but it did compile.

Does LLFIO have a kernel requirement? I see **sendfile** is used elsewhere in the code. If it is okay to use **sendfile** what should the offset be?

**Comment by ned14** [comment]
I've added a supported OS kernel versions statement to the docs. I've also replaced copy_file_range() with its syscall alternative. Let me know if you need anything else.
