### ISSUE TITLE
Account for thread_log_level removal

### ISSUE THREAD

**Issue by johelegp** [ned14/llfio#63]
https://github.com/ned14/llfio/commit/5b19817f220f6fce25b935717acb000903cf7a16 has to account for https://github.com/ned14/quickcpplib/commit/cd8131d3a4104ce1857f48279eb3b10999dd66d4.

**Comment by ned14** [comment]
Is this fixed now?

**Comment by ned14** [comment]
Closing due to lack of feedback.

**Comment by johelegp** [comment]
Sorry. I have this in my inbox, waiting for the time I can test it again. I should have told you that.
