### ISSUE TITLE
Does this project offer async io framework?

### ISSUE THREAD

**Issue by pahome** [ned14/llfio#64]
Execuse me,

I want to find library which supports async. io (not network) and find here.

I read about document and still don't understand the purpose of this project(It might some professional nouns I don't understand).

Does this project offer fast io framework for specific storage device which supports Storage Class Memory (SCM)/Direct Access Storage (DAX) ? Or it fits my scenario?

thx

**Comment by ned14** [comment]
Async file i/o is usually slower than sync file i/o, for most applications and use cases. If you need file i/o concurrency, a pool of kernel threads working on memory mapped files is portable, works well on all platforms, and its performance is very hard to beat with any async file i/o implementation. LLFIO provides a pluggable interface for third party asynchronous i/o engines. It is only really useful for the low level pipe and socket handle implementations.

If you're on a very recent Linux kernel, you can try using io_uring directly. It's great for network i/o, but the gains aren't really there for file i/o. Memory mapped files are very fast, most of the time. LLFIO has the reference implementation for what is currently expected to become `std::mapped_file_handle`, see what you make of it.
