### ISSUE TITLE
missing headers for mac os prebuilt-version 

### ISSUE THREAD

**Issue by yuyoyuppe** [ned14/llfio#67]
I've tried downloading multiple tgz from https://github.com/ned14/llfio/releases, but they all seem to miss `llfio.hpp` and a bunch of other stuff. Perhaps I'm doing something wrong though! It'd be also great to include quickcpplib, so it's self-contained!

**Comment by ned14** [comment]
I do apologise. I checked the Windows ZIP after I ported the script to github actions, I just assumed the others were complete as well. All are missing quickcpplib and outcome in any case.

Thanks for the bug report, I'll get that fixed tomorrow morning.

**Comment by yuyoyuppe** [comment]
@ned14 thanks!

**Comment by ned14** [comment]
Sorry this took so long. I have had very little free time in the mornings before work this week. Can you try the binaries at https://github.com/ned14/llfio/releases/tag/all_tests_passed_0e304a916da69b0367407bea496edd6477fed16d and tell me if they are complete? I don't have a Macintosh, so all my development for Mac OS is done blind.

**Comment by yuyoyuppe** [comment]
@ned14 alright, I'll check in a ~few days and follow up!

**Comment by yuyoyuppe** [comment]
it works now, thank you
