### ISSUE TITLE
vcpkg support?

### ISSUE THREAD

**Issue by feverzsj** [ned14/llfio#69]
It would be nicer if there was a vcpkg port for this lib. So more people can use/test this lib easily.

**Comment by ned14** [comment]
vcpkg requires libraries they supply to operate a formal published release cycle. Until Nov 2020 LLFIO didn't do that, and so vcpkg wouldn't accept LLFIO.

I have asked at https://github.com/microsoft/vcpkg/issues/15563 whether things have now changed. Thanks for your interest in LLFIO.

**Comment by feverzsj** [comment]
I think the minimal requirement of vcpkg is a stable git commit-ish. User can always install head version with --head. Even if official vcpkg doesn't accept llfio, user can just drop the port in ports folder and use it.

**Comment by ned14** [comment]
llfio is now in vcpkg! Thanks for the BR.
