### ISSUE TITLE
`__cpp_modules` now defined in latest MSVC (version > 16.9)

### ISSUE THREAD

**Issue by BurningEnlightenment** [ned14/llfio#75]
https://github.com/ned14/llfio/blob/17d8156ac89e3b8c6aa19a14e0dd723bd65e0902/include/llfio/v2.0/llfio.hpp#L37

I guess this should get the same treatment as https://github.com/ned14/outcome/issues/246. Interestingly it doesn't cause build or test failures for me, but the EDG compiler frontend gets extremely confused.

**Comment by ned14** [comment]
Fixed. Thanks for the report!
