### ISSUE TITLE
Installation incomplete

### ISSUE THREAD

**Issue by harryherold** [ned14/llfio#8]
I build and installed afio without any error/warning.
When I tried to build an example, I got the following error:
```
In file included from /usr/local/include/afio/afio/v2.0/afio.hpp:58:0,
                 from /usr/local/include/afio/afio/afio.hpp:18,
                 from /usr/local/include/afio/afio.hpp:1,
                 from afio_write.cpp:5:
/usr/local/include/afio/afio/v2.0/config.hpp:112:10: fatal error: quickcpplib/include/cpp_feature.h: No such file or directory
 #include "quickcpplib/include/cpp_feature.h"
```
The error can be fixed by providing the include path of the build sources to the compiler.
```
g++ -I/opt/afio/include/afio/v2.0 -Wall -std=c++17 afio_write.cpp -o afio_write  -lstdc++fs -lpthread -ldl -lrt
```

**Comment by ned14** [comment]
Hmm, that's odd. Including that path should search the directory which config.hpp is in. I'll see if I can replicate the same problem here. Thanks for reporting this.

**Comment by ned14** [comment]
Ok, I did the following in a new directory:

```
git clone --recursive https://github.com/ned14/afio.git
cd afio/example
g++-7 -o use_cases use_cases.cpp -lstdc++fs -lrt -lpthread -ldl
```

And it compiled perfectly. Can you confirm this works on your machine as well?

**Comment by ned14** [comment]
Closing due to lack of feedback
